[build]
# Use all available CPU cores for parallel compilation
jobs = 8

# Use faster linker on macOS
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Optimize incremental compilation
[profile.dev]
incremental = true
debug = 1        # Reduce debug info for faster builds
opt-level = 1    # Small optimization for better dev performance

# Faster release builds
[profile.release]
lto = "thin"     # Thin LTO for faster builds
codegen-units = 1
panic = "abort"
strip = true     # Remove debug symbols

# Fast dev profile for Tauri dependencies
[profile.dev.package."*"]
opt-level = 2    # Optimize dependencies even in dev mode

# Network settings
[net]
retry = 2
git-fetch-with-cli = true

# Registry settings for faster crate downloading
[registries.crates-io]
protocol = "sparse"
