[build]
jobs = 4                    # Reduce from 8 to avoid overloading

[target.aarch64-apple-darwin]
# Use default system linker (clang) instead of lld
linker = "clang"

[target.x86_64-apple-darwin] 
# Use default system linker (clang) instead of lld
linker = "clang"

[profile.dev]
# Optimize dependencies for faster builds
opt-level = 1
# Disable debug info for dependencies to speed up builds
debug = 0
# Enable incremental compilation
incremental = true
# Reduce debuginfo for our code only
[profile.dev.package."*"]
opt-level = 3
debug = false
